# Generated by Django 2.2.2 on 2019-08-10 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='others', max_length=45)),
                ('tag', models.CharField(default='empty', max_length=450)),
            ],
            options={
                'db_table': 'category_tag',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField(default='0')),
                ('old_price', models.FloatField(default='0')),
                ('price', models.FloatField(default='0')),
                ('discount', models.FloatField(default='0')),
                ('rating', models.IntegerField(default='0')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.CategoryTag')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superCategory', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'super_category',
            },
        ),
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topCategory', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'top_category',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wish_list',
            },
        ),
        migrations.CreateModel(
            name='TopSuper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SuperCategory')),
                ('topCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.TopCategory')),
            ],
            options={
                'db_table': 'top_super',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Shop')),
            ],
            options={
                'db_table': 'shop_product',
            },
        ),
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('amount', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_log',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=45)),
                ('birth_year', models.DateField()),
                ('profession', models.CharField(blank=True, max_length=45, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('bkash_account_no', models.CharField(max_length=45)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=45)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_review',
            },
        ),
        migrations.AddField(
            model_name='categorytag',
            name='superCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SuperCategory'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
