# Generated by Django 2.2.2 on 2019-08-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190810_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.CharField(max_length=2000),
        ),
    ]
