# Generated by Django 2.2.2 on 2019-06-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_discountdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStorage',
            fields=[
                ('idshop_storage', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shop_storage',
                'managed': False,
            },
        ),
    ]
