# Generated by Django 2.2.2 on 2019-07-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shopstorage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
    ]
