# Generated by Django 2.2.2 on 2019-08-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190810_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_year',
        ),
    ]
