# Generated by Django 2.2.2 on 2019-07-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190701_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='E:\\orange.jpg', max_length=2046),
            preserve_default=False,
        ),
    ]
