# Generated by Django 2.2.2 on 2019-08-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_profile_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='foo', max_length=45),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='foo', max_length=45),
        ),
    ]
