# Generated by Django 2.2.2 on 2019-08-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190822_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(default='0'),
        ),
    ]
