# Generated by Django 2.2.2 on 2019-07-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190703_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
    ]
