# Generated by Django 2.2.2 on 2019-09-14 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_purchaselog_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
