# Generated by Django 2.2.2 on 2019-07-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cartdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='discountdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='shoplog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='shopstorage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
