# Generated by Django 2.2.2 on 2019-09-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190914_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaselog',
            old_name='amount',
            new_name='quantity',
        ),
    ]
