# Generated by Django 2.2.2 on 2019-09-14 18:41

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190914_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=products.models.product_image_path),
        ),
    ]
