# Generated by Django 2.2.2 on 2019-09-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190915_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='orderStatus',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Done')], default=0),
        ),
    ]
