# Generated by Django 2.2.2 on 2019-09-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190915_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountDeadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discountStatus',
            field=models.IntegerField(choices=[(1, 'Discount'), (0, 'No discount')], default=0),
        ),
    ]
