# Generated by Django 2.2.2 on 2019-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190703_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('idshopowner', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('mobile_number', models.CharField(blank=True, db_column='Mobile_number', max_length=45, null=True, unique=True)),
                ('email_id', models.CharField(blank=True, db_column='Email_id', max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'shop_owner',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
