# Generated by Django 2.2.2 on 2019-09-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190915_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountDeadline',
            field=models.DateField(null=True),
        ),
    ]
