# Generated by Django 2.2.2 on 2019-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190915_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountDeadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
