# Generated by Django 2.2.2 on 2019-07-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20190710_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
    ]
